import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import logo from "../img/logo.png"
import responsive from "../img/resposive.jpg"
import professional from'../img/professional.jpg'
import heroBg from '../img/hero-bg.jpg'
import plumber from '../img/plumber.png'
// import styles from '@/styles/Home.module.css'
import styles from '@/styles/home.module.sass'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>IBMT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className={styles.header}>
          <Image
            src={logo}
            width={100}
            height={50}
            alt="IBMT logo"
          />
          <nav>
            <a href="">Home</a>
            <a href="">About Us</a>
            <a href="">Services</a>
            <a href="">Products</a>
            <a href="">Contact Us</a>
          </nav>
        </header>
        <section className={styles.hero}
        style={{ background: "url('/hero-bg.jpg')", backgroundRepeat: "no-repeat",
        backgroundSize: "100% 100%" , lineHeight: "5rem"}}>
          <div>

          </div>
          <div>
          <Image
            src={plumber}
            width={100}
            height={200}
            alt="IBMT logo"
          />
          </div>
        </section>
        <section className={styles.who}>
          <h3>Who We Are</h3>
        </section>
        <section className={styles.services}>
        <Image
            src={plumber}
            width={70}
            height={80}
            alt="IBMT logo"
          />
        </section>
        <section className={styles.aboutUs}></section>
        <section className={styles.testimonies}>
          <article>
            <div> <Image
            src={responsive}
            width={100}
            height={50}
            alt="IBMT logo"
          /></div>
            <div>
              <h4>Professional Plumbers</h4>
              <p> "Idris was awesome. Very professional and thorough when addresing our issue. He answered all of my questions and concerns. As well as leaving the area nice and clean. We would definitely use IBMT PlumbTech."</p>
              <small> <span>Yvonne Nelson</span> - Housewife</small>
            </div>
          </article>
          <article>
            <div><Image
            src={professional}
            width={100}
            height={50}
            alt="IBMT logo"
          /></div>
            <div>
              <h4> Resposive Technicians</h4>
              <p> "Ibrahim Yahaya came out to evaluate a noisy sump pump. He explained our options clearly and changed out the poorly installed sump pump for a better model. He showed us before and after pictures and thoroughly went over what was done. We appreciate IBMT Plumbing for their great and reliable service."</p>
              <small> <span> Idris Mustapha </span> - Federal Worker</small>
            </div>
          </article>
        </section>
        <section className={styles.faq}></section>
        <section className={styles.contact}>
          <h3 style={{ gridArea: "contact"}}> Contact Us</h3>
          <div style={{ gridArea: "first"}}>
            <input type="text" name='first' placeholder='First Name'/>
          </div>
          <div style={{ gridArea: "last"}}>
            <input type="text" name='last' placeholder='Last Name'/>
          </div>
          <div style={{ gridArea: "phone"}}>
            <input type="text" name='phone' placeholder='Phone Number'/>
          </div>
          <div style={{ gridArea: "email"}}>
            <input type="text" name='email'  placeholder='Email Address' />
          </div>
          <div style={{ gridArea: "message"}}>
          <textarea required="required" type="text" id="ContactV1Form_ITM0_Message" class="ui-cms-input" name="ContactV1Form$ITM0$Message"></textarea>
          </div>
          <div style={{ gridArea: "button"}} className={styles.btn}>
            <input type="button" value="Send Message" />
          </div>
        </section>
        <footer className={styles.footer}>
          <div className="logo">
          
          <p>  <Image
            src={logo}
            width={100}
            height={50}
            alt="IBMT logo"
          /> IBMT Heating and Plumbing Technology, is the plumbing and HVAC company of choice, providing both residential plumbing & HVAC and commercial plumbing services 24 hours a day, seven days a week.</p>
          </div>
          <div className="services">
            <h3>OUR SERVICES</h3>
            <ul>
              <li>Residential Services</li>
              <li>Heating and Cooling Services</li>
              <li>Bathroom Remodelling</li>
              <li>Kitchen Services</li>
              <li>Commercial Services</li>
              <li>Emergency Services</li>
            </ul>

          </div>
          <div className="quickLinks">
            <h3>QUICK LINKS</h3>
            <nav>
              <a href="">Home</a><a href="">Blogs</a><a href="">About Us</a><a href="">Achievements & Qualities</a><a href=""></a>
            </nav>
          </div>
          <div className="contacts">
            <h3>CONTACT</h3>
            <div>
              <p>No 5 Adebayo Street, Pedro Road, Bariga-Lagos, Nigeria</p>
            </div>
            <div>
              <p>Main: No 49 Amusan Street, Pupoosola Bustop, Okooba, Abule-Egba, Lagos
Office: Abubakar Tafawa Balewa University, Bauchi</p>
            </div>
            <div>
              <p> (+234) 816 179 1297</p>
            </div>
            <div>
              <p>ibmtplumbingheatingtechnology@gmail.com</p>
            </div>
          </div>

        </footer>
      </main>
    </>
  )
}
